name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Boot simulator
      run: xcrun simctl boot "iPhone 11 Pro"
    - name: Boot simulator Again
      run: xcrun simctl boot "iPhone 11 Pro"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
